Library.Web/Areas/Admin/Controllers/CategoryController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Library.Business.Interfaces;
using Library.DTO.DTOs.CategoryDtos;
using Library.Entities.Concreate;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ISubCategoryService _subCategoryService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        public CategoryController(ICategoryService categoryService, ISubCategoryService subCategoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
            _mapper = mapper;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            TempData["Active"] = "category";

            var db_categories = await _categoryService.GetCategoriesWithSubCategoriesAsync();

            var categoryList = new List<CategoryListDto>();

            foreach (var db_category in db_categories)
            {
                var baseCategory = new CategoryListDto();

                baseCategory.Id = db_category.Id;
                baseCategory.Name = db_category.Name;
                baseCategory.SubCategories = db_category.SubCategories;

                categoryList.Add(baseCategory);
            }

            return View(categoryList);
        }

        
        
        [HttpGet]
        public IActionResult Add()
        {
            TempData["Active"] = "category";

            return View(new CategoryAddDto());
        }


        [HttpPost]
        public async Task<IActionResult> Add(CategoryAddDto model)
        {
            TempData["Active"] = "category";

            if (ModelState.IsValid)
            {
                await _categoryService.AddAsync(_mapper.Map<CategoryAddDto, Category>(model));

                return RedirectToAction("Index", "Category");
            }

            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TempData["Active"] = "category";

            var getCategory = await _categoryService.GetCategoriesWithSubCategoriesUsingIdAsync(id);

            var updatedCategory = new CategoryUpdateDto
            {
                Name = getCategory.Name,
                Id = getCategory.Id,
                SubCategories = getCategory.SubCategories
            };

            return View(updatedCategory);
        }


        [HttpPost]
        public async Task<IActionResult> Update(CategoryUpdateDto model)
        {
            TempData["Active"] = "category";

            if (ModelState.IsValid)
            {
                await _categoryService.UpdateAsync(_mapper.Map<CategoryUpdateDto, Category>(model));

                return RedirectToAction("Index", "Category");
            }

            return View(model);
        }

    }

}

Library.Web/Areas/Admin/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using Library.Business.Interfaces;
using Library.DTO.DTOs.SubCategoryDtos;
using Library.Entities.Concreate;

namespace Library.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SubCategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ISubCategoryService _subCategoryService;
        private readonly IMapper _mapper;
        public SubCategoryController(ISubCategoryService subCategoryService, ICategoryService categoryService, IMapper mapper)
        {
            _categoryService = categoryService;
            _subCategoryService = subCategoryService;
            _mapper = mapper;
        }


        [HttpGet]
        public async Task<IActionResult> GetSubCategoriesOfBaseCategory(int BaseCategoryId)
        {
            TempData["Active"] = "category";

            var db_Subcategories = await _subCategoryService.GetSubCategoriesOfBaseCategoryWithIdAsync(BaseCategoryId);

            var SubcategoryList = new List<SubCategoryListDto>();

            foreach (var db_Subcategory in db_Subcategories)
            {
                var subCategory = new SubCategoryListDto();

                subCategory.Id = db_Subcategory.Id;
                subCategory.Name = db_Subcategory.Name;

                SubcategoryList.Add(subCategory);
            }

            var jsonCategories = JsonConvert.SerializeObject(SubcategoryList);

            return Json(jsonCategories);
        }


        [HttpGet]
        public async Task<IActionResult> Add(int baseCategoryId)
        {
            TempData["Active"] = "category";

            var getBaseCategory = await _categoryService.FindByIdAsync(baseCategoryId);

            var updatedCategory = new SubCategoryAddDto
            {
                Category = getBaseCategory,
                CategoryId = getBaseCategory.Id,
                Name = String.Empty
            };

            return View(updatedCategory);

        }


        [HttpPost]
        public async Task<IActionResult> Add(SubCategoryAddDto model)
        {
            TempData["Active"] = "category";

            if (ModelState.IsValid)
            {
                await _subCategoryService.AddAsync(_mapper.Map<SubCategoryAddDto, SubCategory>(model));

                return RedirectToAction("Update", new RouteValueDictionary(
                    new { controller = "Category", action = "Update", id = model.CategoryId }));
            }

            return View(model);
        }



        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            TempData["Active"] = "category";

            var getCategory = await _subCategoryService.GetSubCategoryWithIdAsync(id);

            var updatedCategory = new SubCategoryUpdateDto
            {
                Id = getCategory.Id,
                Name = getCategory.Name,
                CategoryId=getCategory.CategoryId
            };

            return View(updatedCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SubCategoryUpdateDto model)
        {
            TempData["Active"] = "category";

            if (ModelState.IsValid)
            {
                await _subCategoryService.UpdateAsync(_mapper.Map<SubCategoryUpdateDto, SubCategory>(model));

                return RedirectToAction("Index", "Category");
            }

            return View(model);

        }

    }
}

Library.Web/Areas/Admin/Views/Category/Add.cshtml
@model CategoryAddDto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3 mt-2" method="post">
    <div class="form-group">
        <label asp-for="Name">Yeni Kategori Adı</label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" type="text" class="form-control" />
    </div>

    <input type="submit" class="btn btn-sm btn-info" value="Ekle" />

</form>

Library.Web/Areas/Admin/Views/Category/Index.cshtml
@model List<CategoryListDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/select.css">

</head>

<div class="container">
    <div class="row">

        <div class="col-md-4 mt-3">

            <h3 class="text-center">Ana Kategoriler</h3>

            <div class="select">

                <select name="format" id="dropdown">
                    @foreach (var baseCategories in Model)
                    {
                        <option value="@baseCategories.Id" selected>@baseCategories.Name</option>
                    }

                </select>

            </div>

            <div class="p-2 mt-4" id="getSubCategories"></div>

        </div>

        <div class="col-md-8 mt-3">


            @if (Model.Count > 0)
            {
                <a asp-action="Add" asp-controller="Category" class="btn btn-sm btn-info my-2">Yeni Kategori Ekle</a>

                <table class="table table-sm table-hover">

                    <thead>
                        <tr>
                            <th>Ana Kategori</th>
                            <th>Alt Kategoriler</th>
                            <th>İşlem</th>
                        </tr>
                    </thead>

                    <tbody>


                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Name</td>
                                <td>@item.SubCategories.Count</td>
                                <td>
                                    <a asp-action="Update" asp-controller="Category" asp-route-id="@item.Id" class="btn btn-sm btn-info my-2">Düzenle</a>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>

            }
            else
            {
                <div class="text-center mt-3 p-3">
                    <p class="lead">
                        Sistemde Kayıtlı Kategori Bulunamadı
                    </p>
                    <a asp-action="Add" asp-controller="Category" class="btn btn-sm btn-info my-2">Kategori Ekle</a>

                </div>
            }

        </div>

    </div>


</div>






@section Javascript{

    <script type="text/javascript">
        $(document).ready(function () {





            $("#dropdown").change(function () {

                let BaseCategoryId = $('#dropdown :selected').val();

                $.ajax({
                    contentType: "application/json; charset=Utf-8;",
                    dataType: "json",
                    type: "Get",
                    url: "/Admin/SubCategory/GetSubCategoriesOfBaseCategory",
                    data: { BaseCategoryId: BaseCategoryId },
                    success: function (getSubcategories) {
                        let SubcategoriesObject = jQuery.parseJSON(getSubcategories);
                        let htmlString = `<table class="table table-sm table-hover">
                                                            <thead>
                                                                <tr>
                                                                    <th>Alt Kategori</th>
                                                                    <th>İşlem</th>
                                                                </tr>
                                                            </thead>
                                                        <tbody>  `

                        $.each(SubcategoriesObject, (index, value) => {
                            htmlString += `<tr>
                                                              <td> ${value.Name} </td>
                                                              <td>
                                                                    <a href="/Admin/SubCategory/Update/${value.Id}" id=${value.Id} class="btn btn-sm btn-info my-2">Düzenle</a>
                                                                  </td>
                                                            </tr>`
                        });

                        htmlString += `</tbody> </table>`;

                        $("#getSubCategories").html(htmlString);
                    }

                });

            });




        });

    </script>
}

Library.Web/Areas/Admin/Views/Category/Update.cshtml
@model CategoryUpdateDto

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form class="w-75 mx-auto p-3 mt-2" method="post">

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Name">Ana Kategori</label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" type="text" class="form-control" />
    </div>

    <a asp-action="Add" asp-controller="SubCategory" asp-route-baseCategoryId="@Model.Id" class="btn btn-sm btn-info my-2">Alt Kategori Ekle</a>


    <br />
    <hr />
    <br />

    <div class="form-group">

        <table class="table table-sm table-hover">

            <thead>
                <tr>
                    <th>Alt Kategoriler</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.SubCategories)
                {
                    <tr>
                        <td>@item.Name</td>
                    </tr>
                }
            </tbody>

        </table>

    </div>

    <a asp-action="Index" asp-controller="Category" class="btn btn-sm btn-warning">Geri</a>

    <input type="submit" class="btn btn-sm btn-info" value="Güncelle" />

</form>